/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTB0 (number 43), J10[2]/A0
  @{ */
#define BOARD_INITPINS_NorteVerde_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_NorteVerde_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_NorteVerde_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_NorteVerde_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                             /* @} */

/*! @name PORTB1 (number 44), J10[4]/A1
  @{ */
#define BOARD_INITPINS_NorteAmarillo_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_NorteAmarillo_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_NorteAmarillo_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_NorteAmarillo_PIN 1U     /*!<@brief PORTB pin index: 1 */
                                                /* @} */

/*! @name PORTB2 (number 45), J10[6]/A2
  @{ */
#define BOARD_INITPINS_NorteRojo_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_NorteRojo_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_NorteRojo_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_NorteRojo_PIN 2U     /*!<@brief PORTB pin index: 2 */
                                            /* @} */

/*! @name PORTB3 (number 46), J10[8]/A3
  @{ */
#define BOARD_INITPINS_NorteVuelta_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_NorteVuelta_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_NorteVuelta_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_NorteVuelta_PIN 3U     /*!<@brief PORTB pin index: 3 */
                                              /* @} */

/*! @name PORTE20 (number 13), J10[1]
  @{ */
#define BOARD_INITPINS_SurVerde_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_SurVerde_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_SurVerde_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_SurVerde_PIN 20U    /*!<@brief PORTE pin index: 20 */
                                           /* @} */

/*! @name PORTE21 (number 14), J10[3]
  @{ */
#define BOARD_INITPINS_SurAmarillo_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_SurAmarillo_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_SurAmarillo_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_SurAmarillo_PIN 21U    /*!<@brief PORTE pin index: 21 */
                                              /* @} */

/*! @name PORTE22 (number 15), J10[5]
  @{ */
#define BOARD_INITPINS_SurRojo_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_SurRojo_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_SurRojo_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_SurRojo_PIN 22U    /*!<@brief PORTE pin index: 22 */
                                          /* @} */

/*! @name PORTE23 (number 16), J10[7]
  @{ */
#define BOARD_INITPINS_SurVuelta_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_SurVuelta_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_SurVuelta_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_SurVuelta_PIN 23U    /*!<@brief PORTE pin index: 23 */
                                            /* @} */

/*! @name PORTE29 (number 21), J10[9]
  @{ */
#define BOARD_INITPINS_SurBoton_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_SurBoton_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_SurBoton_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_SurBoton_PIN 29U    /*!<@brief PORTE pin index: 29 */
                                           /* @} */

/*! @name PORTC0 (number 55), J1[3]
  @{ */
#define BOARD_INITPINS_EsteVuelta_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_EsteVuelta_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_EsteVuelta_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_EsteVuelta_PIN 0U     /*!<@brief PORTC pin index: 0 */
                                             /* @} */

/*! @name PORTC5 (number 62), J1[9]
  @{ */
#define BOARD_INITPINS_EsteVerde_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_EsteVerde_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_EsteVerde_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_EsteVerde_PIN 5U     /*!<@brief PORTC pin index: 5 */
                                            /* @} */

/*! @name PORTC4 (number 61), J1[7]
  @{ */
#define BOARD_INITPINS_EsteAmarillo_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_EsteAmarillo_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_EsteAmarillo_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_EsteAmarillo_PIN 4U     /*!<@brief PORTC pin index: 4 */
                                               /* @} */

/*! @name PORTC3 (number 58), J1[5]
  @{ */
#define BOARD_INITPINS_EsteRojo_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_EsteRojo_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_EsteRojo_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_EsteRojo_PIN 3U     /*!<@brief PORTC pin index: 3 */
                                           /* @} */

/*! @name PORTC7 (number 64), J1[1]
  @{ */
#define BOARD_INITPINS_EsteBoton_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_EsteBoton_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_EsteBoton_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_EsteBoton_PIN 7U     /*!<@brief PORTC pin index: 7 */
                                            /* @} */

/*! @name PORTA4 (number 30), J1[10]/D4
  @{ */
#define BOARD_INITPINS_OesteVerde_FGPIO FGPIOA /*!<@brief FGPIO device name: FGPIOA */
#define BOARD_INITPINS_OesteVerde_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_OesteVerde_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_OesteVerde_PIN 4U     /*!<@brief PORTA pin index: 4 */
                                             /* @} */

/*! @name PORTA12 (number 32), J1[8]/D3
  @{ */
#define BOARD_INITPINS_OesteAmarillo_FGPIO FGPIOA /*!<@brief FGPIO device name: FGPIOA */
#define BOARD_INITPINS_OesteAmarillo_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_OesteAmarillo_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_OesteAmarillo_PIN 12U    /*!<@brief PORTA pin index: 12 */
                                                /* @} */

/*! @name PORTA1 (number 27), J1[2]/D0/UART0_RX
  @{ */
#define BOARD_INITPINS_OesteBoton_FGPIO FGPIOA /*!<@brief FGPIO device name: FGPIOA */
#define BOARD_INITPINS_OesteBoton_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_OesteBoton_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_OesteBoton_PIN 1U     /*!<@brief PORTA pin index: 1 */
                                             /* @} */

/*! @name PORTA2 (number 28), J1[4]/D1/UART0_TX
  @{ */
#define BOARD_INITPINS_OesteVuelta_FGPIO FGPIOA /*!<@brief FGPIO device name: FGPIOA */
#define BOARD_INITPINS_OesteVuelta_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_OesteVuelta_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_OesteVuelta_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                              /* @} */

/*! @name PORTD4 (number 77), J1[6]/D2
  @{ */
#define BOARD_INITPINS_OesteRojo_FGPIO FGPIOD /*!<@brief FGPIO device name: FGPIOD */
#define BOARD_INITPINS_OesteRojo_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_OesteRojo_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_OesteRojo_PIN 4U     /*!<@brief PORTD pin index: 4 */
                                            /* @} */

/*! @name PORTC2 (number 57), J10[10]/A4
  @{ */
#define BOARD_INITPINS_NorteBoton_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_NorteBoton_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_NorteBoton_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_NorteBoton_PIN 2U     /*!<@brief PORTC pin index: 2 */
                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
